using LibreHardwareMonitor.Hardware;
using System;
using System.IO;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text;

namespace Fanzi.FanControl.Services;

/// <summary>
/// Generates a comprehensive plain-text hardware/system report — useful for support
/// tickets, sharing your rig spec, or comparing temps across days.
/// </summary>
public sealed class HardwareReportService : IDisposable
{
    private readonly Computer _computer;

    public HardwareReportService()
    {
        _computer = new Computer
        {
            IsCpuEnabled = true,
            IsGpuEnabled = true,
            IsMemoryEnabled = true,
            IsMotherboardEnabled = true,
            IsControllerEnabled = true,
            IsStorageEnabled = true,
            IsBatteryEnabled = true,
            IsPsuEnabled = true,
            IsNetworkEnabled = true,
        };
        _computer.Open();
    }

    public string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("FANZI HARDWARE REPORT");
        sb.AppendLine("=====================");
        sb.AppendLine($"Generated:        {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Machine name:     {Environment.MachineName}");
        sb.AppendLine($"User:             {Environment.UserName}");
        sb.AppendLine($"OS:               {RuntimeInformation.OSDescription}");
        sb.AppendLine($"Architecture:     {RuntimeInformation.OSArchitecture}");
        sb.AppendLine($"CPU cores:        {Environment.ProcessorCount} logical");
        sb.AppendLine($"System uptime:    {TimeSpan.FromMilliseconds(Environment.TickCount64):d\\.hh\\:mm\\:ss}");
        sb.AppendLine();

        foreach (var hw in _computer.Hardware)
        {
            hw.Update();
            foreach (var sub in hw.SubHardware) sub.Update();
            sb.AppendLine($"── {hw.HardwareType}: {hw.Name} ──");

            foreach (var sensor in hw.Sensors)
            {
                if (sensor.Value.HasValue)
                {
                    sb.AppendLine($"  {sensor.SensorType,-14} {sensor.Name,-40} {sensor.Value.Value:F2}{UnitFor(sensor.SensorType)}");
                }
            }

            foreach (var sub in hw.SubHardware)
            {
                sb.AppendLine($"  SubHardware: {sub.Name}");
                foreach (var sensor in sub.Sensors)
                {
                    if (sensor.Value.HasValue)
                    {
                        sb.AppendLine($"    {sensor.SensorType,-14} {sensor.Name,-40} {sensor.Value.Value:F2}{UnitFor(sensor.SensorType)}");
                    }
                }
            }
            sb.AppendLine();
        }

        sb.AppendLine("── Storage drives ──");
        foreach (var d in DriveInfo.GetDrives())
        {
            try
            {
                if (!d.IsReady) continue;
                sb.AppendLine($"  {d.Name,-6} {d.DriveType,-12} {d.DriveFormat,-6} " +
                              $"{d.TotalSize / 1024.0 / 1024.0 / 1024.0,8:F1} GB total, " +
                              $"{d.AvailableFreeSpace / 1024.0 / 1024.0 / 1024.0,8:F1} GB free, " +
                              $"{d.VolumeLabel}");
            }
            catch { }
        }
        sb.AppendLine();

        sb.AppendLine("── Network adapters ──");
        foreach (var nic in NetworkInterface.GetAllNetworkInterfaces())
        {
            if (nic.OperationalStatus != OperationalStatus.Up) continue;
            sb.AppendLine($"  {nic.Name} | {nic.NetworkInterfaceType} | {nic.Speed:N0} bps | {nic.Description}");
        }
        sb.AppendLine();

        sb.AppendLine("Report generated by FANZI v2.0 — © 2018-2026 Antwerp Designs");
        return sb.ToString();
    }

    public string SaveToDefaultLocation()
    {
        string dir = Path.Combine(ProfileManagerService.DefaultProfileDir, "..", "Reports");
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, $"FANZI-Report-{DateTime.Now:yyyyMMdd-HHmmss}.txt");
        File.WriteAllText(path, Generate());
        return Path.GetFullPath(path);
    }

    private static string UnitFor(SensorType t) => t switch
    {
        SensorType.Temperature => " °C",
        SensorType.Load => " %",
        SensorType.Fan => " RPM",
        SensorType.Flow => " L/h",
        SensorType.Control => " %",
        SensorType.Level => " %",
        SensorType.Power => " W",
        SensorType.Data => " GB",
        SensorType.SmallData => " MB",
        SensorType.Throughput => " B/s",
        SensorType.Clock => " MHz",
        SensorType.Voltage => " V",
        SensorType.Current => " A",
        SensorType.Frequency => " Hz",
        SensorType.Factor => "",
        _ => "",
    };

    public void Dispose() => _computer.Close();
}
